### ISSUE TITLE
请问一下，子应用的路由实在哪里注册的，因为你在子应用那里有一个判断。用qiankun启动，子引用的路由没有注册

### ISSUE THREAD

**Issue by txincrystal** [fengxianqi/qiankun-example#10]

**Comment by fengxianqi** [comment]
qiankun启动时，需要指定`activeRule`来表示用哪个路径启动哪个子应用，是放在[基座即main里面](https://github.com/fengxianqi/qiankun-example/blob/master/main/src/micro-app.js)。
而进入子应用的路由后，是子应用自己接管了，子应用自己定义。
