### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by YvanSuen** [fengxianqi/qiankun-example#12]
按照部署过程操作后，无法启动
错误信息
available via `npm run-script`:
  install:main
    cd main && npm i
  install:sub-vue
    cd sub-vue && npm i
  start:sub-vue
    cd sub-vue && npm start
  start:main
    cd main && npm start
  start:sub-html
    cd sub-html && npm start
  build
    npm-run-all build:* && bash ./scripts/bundle.sh
  build:sub-vue
    cd sub-vue && npm run build
  build:sub-html
    cd sub-html && npm run build
  build:main
    cd main && npm run build

**Comment by fengxianqi** [comment]
是不是没有先通过`npm i`安装依赖呀

**Comment by YvanSuen** [comment]
> 是不是没有先通过`npm i`安装依赖呀

按照流程安装，VUE的无法启动，其他都可以

**Comment by YvanSuen** [comment]
> 是不是没有先通过`npm i`安装依赖呀

Compiled successfully!

You can now view sub-react in the browser.

  Local:            http://localhost:7788/subapp/sub-react   
  On Your Network:  http://192.168.56.1:7788/subapp/sub-react

Note that the development build is not optimized.
To create a production build, use yarn build.

[2021-09-23T03:35:13.825Z]  "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52"
(node:11172) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2021-09-23T03:35:13.911Z]  "GET /js/main.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52"

启动成功，访问VUE子程序就报错误了

**Comment by YvanSuen** [comment]
![image](https://user-images.githubusercontent.com/76144573/134453013-e1531517-4625-45a0-88dc-e2268c2acb89.png)

**Comment by YvanSuen** [comment]
![image](https://user-images.githubusercontent.com/76144573/134631814-77a9ccdc-3245-4bc3-82f9-7f696fb5604e.png)
是不是因为这个跨域问题，但react可以使用啊

**Comment by Pengzhenglong** [comment]
'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by fengxianqi** [comment]
> 

最新的已修复

**Comment by fengxianqi** [comment]
https://github.com/fengxianqi/qiankun-example/pull/13
