### ISSUE TITLE
clone下来后npm install  报错，但是npm-run-all 确实已经安装了

### ISSUE THREAD

**Issue by yaozoo** [fengxianqi/qiankun-example#14]
![image](https://user-images.githubusercontent.com/39789970/138553215-642060ae-a98e-4d93-b1af-dccc107e6d2a.png)
![image](https://user-images.githubusercontent.com/39789970/138553322-f62879af-4f93-4d23-bd2b-90f051e03a1c.png)

**Comment by elderdog** [comment]
![image](https://user-images.githubusercontent.com/21102079/138856925-e0d407fd-e6dc-4fd5-9b18-652f0574760d.png)
你这个package-lock.json中这个依赖的配置跟仓库里的长得不太一样，看看项目node_modules里有没有这个依赖
