### ISSUE TITLE
项目全部安装 依赖，切换菜单报错

### ISSUE THREAD

**Issue by changchengyan** [fengxianqi/qiankun-example#15]
细节描述， 初始化 的菜单是可以进去的 ，但是其他菜单切换 就是进不去，但是切换到 初始化菜单本身没有问题

**Comment by changchengyan** [comment]
错误 代码  Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch

依赖我是  逐个安装到各自的 目录下的

**Comment by Mrchen128** [comment]
me too

**Comment by Mrchen128** [comment]
> 错误 代码 Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch
> 
> 依赖我是 逐个安装到各自的 目录下的

解决了，在package.json scripts中添加"install:sub-html": "cd sub-html && npm i",即可

**Comment by fengxianqi** [comment]
https://github.com/fengxianqi/qiankun-example/pull/13
