### ISSUE TITLE
问题请教：子应用和父应用遮罩覆盖问题

### ISSUE THREAD

**Issue by zhuanghongbin** [fengxianqi/qiankun-example#16]
子应用使用elemenui框架那种dialog或者抽屉组件，遮罩层挂载到了父应用的body，子应用的实际内容被遮罩层遮住，这种要怎么处理，如果只挂载的子组件本身，那父应用，一些公共的地方又没遮住

**Comment by fengxianqi** [comment]
是否可以通过改子应用实际内容的z-index来实现不被遮罩呢，建议show case一下

**Comment by zhuanghongbin** [comment]
非常感谢，好像没这个问题了
