### ISSUE TITLE
分仓库管理子应用

### ISSUE THREAD

**Issue by Leyu801** [fengxianqi/qiankun-example#2]
_若项目有CI/CD，只修改了某个子应用的代码，但代码提交会同时触发所有子应用构建，牵一发动全身，是不合理的_。

请问，独立仓库之后，基座怎么取子应用呢（子应用打包完成后， 怎么放到基座中？）。

**Comment by fengxianqi** [comment]
子应用和基座是可以分开跑的，他们可以看做是两个不同的网站。基座是通过http地址获取子应用的，这个地址在注册子应用时指定。
