### ISSUE TITLE
基座跑起来会有跨域问题，想问下

### ISSUE THREAD

**Issue by yousmellnice** [fengxianqi/qiankun-example#21]
![Uploading image.png…]()
想问下怎么解决

**Comment by fengxianqi** [comment]
图片没上传成功，再上传来看看

**Comment by yousmellnice** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/69194614/182269539-8e3d8da1-8ed0-4355-af31-1aa5aa046a82.png">
subVue 被拒绝访问了，

**Comment by yousmellnice** [comment]
fetch失败，查了下说是跨域？但是我看sub-vue中也是配了'Access-Control-Allow-Origin': '*'，百思不得解

**Comment by fengxianqi** [comment]
这不是跨域，可能是sub-vue子应用没有启动成功，你单独访问一下sub-vue子应用看看能正常吗

**Comment by yousmellnice** [comment]
oooo,子应用app是可以单独访问的
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/69194614/182287114-b4d3b577-ef1f-4a4a-90fe-c87a9b85f6ff.png">

**Comment by fengxianqi** [comment]
demo项目有增删什么代码吗？看看有没第三方资源啥的，参考这里： https://github.com/umijs/qiankun/issues/1331

**Comment by yousmellnice** [comment]
难搞哦，没有修改过源代码；demo中也没见有什么第三方资源。。。。。。。

**Comment by lucky-zouzou** [comment]
这个看起来不像是跨域，会不会是你的webpack版本比较新，我今天遇到了类似的报错，把子应用里config.js里的jsonpFunction改成chunkLoadingGlobal

**Comment by daoliang** [comment]
如果说我要加一个外部的子应用，应该怎么加啊

我是直接在micro-app.js

{
    name: 'text',
    entry: '//localhost:8080/',
    activeRule: '/text'
  }

一直提示Uncaught TypeError: Failed to fetch

这个外部的子应用，跟qiankun 不是同一目录

**Comment by XiaoYT** [comment]
> 如果说我要加一个外部的子应用，应该怎么加啊
> 
> 我是直接在micro-app.js
> 
> { name: 'text', entry: '//localhost:8080/', activeRule: '/text' }
> 
> 一直提示Uncaught TypeError: Failed to fetch
> 
> 这个外部的子应用，跟qiankun 不是同一目录

子项目run了没，你还要去main文件下的.env声明一下你添加的子应用的端口号

**Comment by XiaoYT** [comment]
![image](https://user-images.githubusercontent.com/17793358/197124797-3305355a-90af-41d9-901f-ac0f9fcc6a34.png)
跨域问题应该是像我这样的吧，我是真的遇到跨域问题了，主应用我配置了proxy但是没有起作用，怎么搞呢

**Comment by daoliang** [comment]
> >

我大概知道问题在哪了，我应该是跨域的问题，子项目run 起来了。我看下，怎么解决这个跨域的问题。

**Comment by guxuerui** [comment]
本地的话， 把 `127.0.0.1` 改成 `localhost`  就不跨域了

```js
import { registerMicroApps, start } from 'qiankun'

registerMicroApps([
  {
    name: "vue-app", // 必须与微应用注册名字相同
    entry: "http://localhost:5174", // 入口路径，开发时为微应用所启本地服务，上线时为微应用线上路径
    container: "#vue-app-container", // 微应用挂载的节点
    activeRule: "/micro-vue", // 当访问路由为 /micro-vue 时加载微应用
    props: {
      msg: "我是来自主应用的值-vue", // 主应用向微应用传递参数
    },
  },
  {
    name: "react-app",
    entry: "http://localhost:5175",
    container: "#react-app-container",
    activeRule: "/micro-react",
    props: {
      msg: "我是来自主应用的值-react",
    },
  }
]);
```
