### ISSUE TITLE
sub-vue\src\main.js  common库是自定义的吗？

### ISSUE THREAD

**Issue by zhanhuixian** [fengxianqi/qiankun-example#24]
//sub-vue\src\main.js
`
import { store as commonStore } from 'common'
`

在node_modules：/qiankun-example/sub-vue/node_modules/common/src/index"路径中可以找到

请问下common库是自定义的吗?
如果是，有如下问题想请教下：
1. 如何实现自定义库？
2. 为什么要放在node_modules目录下，而不是利用新建公共文件的方式引用？

**Comment by fengxianqi** [comment]
可以看下README的介绍文章，里面有讲：https://juejin.cn/post/6875462470593904653
