### ISSUE TITLE
请教一下，分仓库管理子应用，子应用也是分开管理么？每个都是一个repo，还是子应用仍在同一个repo下

### ISSUE THREAD

**Issue by Leyu801** [fengxianqi/qiankun-example#3]
1. 比如我有10几个子应用，每个子应用都是一个单独的git仓库，因为我们遵循gitflow的流程，如果在某一期的修改中，只修改了其中3个应用，那在上线测试的时候，如何做到10几个子应用同时打出release分支呢？
2. 如果分仓库管理了每个子应用，那`git submodule和git subtree都是很好的子仓库管理方案，但缺点是每次子应用变更后，聚合库还得同步一次变更。`这个是不是就不在场景使用了，看了下gitsubmoudle使用都是在一个仓库里使用

**Comment by fengxianqi** [comment]
## 第一个问题：
发布上线的版本管理有两种形式：
- 所有子应用的版本和产品版本保持一致
- 所有子应用的版本和产品版本不保持一致

首先是第一种方案，项目里面有10个子应用，在一个迭代里只修改了3个，产品版本迭代到v2.0.0，此时要求这10个子应用都要打出v2.0.0的版本，但是其中有7个子应用是没有任何修改的，只是纯粹为了与产品版本保持一致打了一个无任何改动的分支或tag，这种做法对一个独立的仓库来说不太合理；而且如果上线后某个子应用出现紧急bug需要hotfix，这又会拖累其他子应用又打一次无意义的tag。

所以在我们这里选了第二种方案，即允许出现产品版本是v2.0.0，子应用A是v2.0.0，B是v1.9.0，C是v1.8.0这样。这样的好处是迭代时只针对有修改的应用的版本会向前滚动，子应用和整个产品的版本不再耦合在一起，更符合qiankun的理念。但坏处就是难以管理，版本会非常乱。特别是当需要回滚时，我们难以找回产品的上一个版本都有哪些子应用。这就需要我们建立一个微应用管理的一个平台，即至少要做到：发版后，我们将当前的产品版本下的各个子应用的版本都记录下来，当要回滚时，我们就可以很快地找到产品版本对应的子应用版本了。

这个平台我们是想结合gitlab的cicd能力整合起来，做到更多的自动化，目前还在探索中开发，欢迎一起讨论。


## 第二个问题
> git submodule和git subtree都是很好的子仓库管理方案，但缺点是每次子应用变更后，聚合库还得同步一次变更

这个是针对聚合库来说的，聚合库是集合了所有子应用在一个文件夹内，是为了在开发环境能够完整地一键跑起整个产品。这个聚合库下会有多个独立的git仓库的子应用，所以说方案有git submodule和git subtree等。

**Comment by xuejunnan** [comment]
请问是否有主应用都是在不同的git repo 的例子，具体看一下吗

**Comment by Leyu801** [comment]
我理解你第一个问题方案2的意思了，我现在还没做到版本子应用随着部署发布版本也更新。（那你们是怎么做的版本管理呀）
我们现在也是使用的gitlab的cicd,只不过统一针对了一个分支去构建。

**Comment by Leyu801** [comment]
> ## 第二个问题
> > git submodule和git subtree都是很好的子仓库管理方案，但缺点是每次子应用变更后，聚合库还得同步一次变更
> 
> 这个是针对聚合库来说的，聚合库是集合了所有子应用在一个文件夹内，是为了在开发环境能够完整地一键跑起整个产品。这个聚合库下会有多个独立的git仓库的子应用，所以说方案有git submodule和git subtree等。

我现在比较low，就只支持了单独联调，还没支持聚合

**Comment by fengxianqi** [comment]
> 请问是否有主应用都是在不同的git repo 的例子，具体看一下吗

你可以尝试先根据我的文章描述自己搭一下的哈，因为我线上搞那么多仓库是没啥意义的，遇到不懂的可以直接评论问一下的哈。

**Comment by fengxianqi** [comment]
> 我们现在也是使用的gitlab的cicd,只不过统一针对了一个分支去构建。

我们目前是人工记录，但正在自发搞一下微应用管理平台，调用gitlab的cicd能力做构建，还在探索，有机会的话我后面再分享下文章，欢迎关注。
