### ISSUE TITLE
Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch

### ISSUE THREAD

**Issue by junziyuyi** [fengxianqi/qiankun-example#4]
请教一下 代码报错 Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch

**Comment by fengxianqi** [comment]
> 请教一下 代码报错 Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch

初步判断是没有启动sub-vue子应用或路径端口不对，若无法解决麻烦提供下复现步骤。

**Comment by yuleiQ** [comment]
@fengxianqi  朋友 再问你个问题，请问如果子应用load失败了，如何二次load啊？
问题描述：
Uncaught TypeError: application 'sub1' died in status LOADING_SOURCE_CODE: network error，出现这种情况是因为我们后端单独部署子应用A出现404。此时我会跳转到一个404的友好页面，然后我跳转到B（页面正常加载），在点击跳转A页面时，这时其实A并不会重新load的，我如何让A重新load呢？

**Comment by jackywq** [comment]
> 请教一下 代码报错 Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch

我的也是如此

**Comment by jackywq** [comment]
> > 请教一下 代码报错 Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch
> 
> 初步判断是没有启动sub-vue子应用或路径端口不对，若无法解决麻烦提供下复现步骤。

复现步骤： 
1. git clone 项目地址
2. npm install
3. npm run start

页面显示：
![image](https://user-images.githubusercontent.com/21954704/105141698-83a52f80-5b34-11eb-9e21-39ac3c0b6a27.png)

报错信息：
![image](https://user-images.githubusercontent.com/21954704/105141711-8dc72e00-5b34-11eb-96c9-ff03dfd70651.png)

**Comment by yuleiQ** [comment]
> @fengxianqi 朋友 再问你个问题，请问如果子应用load失败了，如何二次load啊？
> 问题描述：
> Uncaught TypeError: application 'sub1' died in status LOADING_SOURCE_CODE: network error，出现这种情况是因为我们后端单独部署子应用A出现404。此时我会跳转到一个404的友好页面，然后我跳转到B（页面正常加载），在点击跳转A页面时，这时其实A并不会重新load的，我如何让A重新load呢？

已解决 忽略

**Comment by Leyu801** [comment]
> > > 请教一下 代码报错 Uncaught TypeError: application 'sub-vue' died in status LOADING_SOURCE_CODE: Failed to fetch
> > 
> > 
> > 初步判断是没有启动sub-vue子应用或路径端口不对，若无法解决麻烦提供下复现步骤。
> 
> 复现步骤：
> 
> 1. git clone 项目地址
> 2. npm install
> 3. npm run start
> 
> 页面显示：
> ![image](https://user-images.githubusercontent.com/21954704/105141698-83a52f80-5b34-11eb-9e21-39ac3c0b6a27.png)
> 
> 报错信息：
> ![image](https://user-images.githubusercontent.com/21954704/105141711-8dc72e00-5b34-11eb-96c9-ff03dfd70651.png)

你启动子应用了么

**Comment by william-xue** [comment]
也是这样

**Comment by fengxianqi** [comment]
建议单独访问子应用链接查看子应用是否已启动来排查一下
