### ISSUE TITLE
[common store] 封装的 GlobalState这一块，怎么在react或者html项目里应用？

### ISSUE THREAD

**Issue by zhangyuanliang** [fengxianqi/qiankun-example#6]
项目里把GlobalState封装到了common项目里，sub-vue进行了引用。但是在react和jquery的html项目里可以引用吗？具体怎么用，特别是jquery的html项目中

**Comment by fengxianqi** [comment]
这个是为vue子应用封装的，强依赖于vuex，所以react和jq的项目不能用。其他项目可以通过父应用下发的state做进一步类似的封装

**Comment by zhangyuanliang** [comment]
还有一点，想问下，在子应用之间怎么可持续性共享数据？

**Comment by fengxianqi** [comment]
> 还有一点，想问下，在子应用之间怎么可持续性共享数据？

可以使用qiankun提供的`onGlobalStateChange`方法来监听变化。
