### ISSUE TITLE
build的bash指令，是专门给CI/CD用的吗？本地打包好像用不了bash命令

### ISSUE THREAD

**Issue by ccysmd** [fengxianqi/qiankun-example#9]

**Comment by fengxianqi** [comment]
1. build命令是将所有主子应用都统一打包到根目录的`dist`文件夹（同时会按部署目录层级来排列），这样比较方便部署，copy整个文件夹就完事了，所以不是专门给ci/cd用的，它只是帮助我们一键打包和整理目录结构。
2. bash是Unix系统才支持的。windows上用`git bash`应该也能跑。
